---

- name: Install docker, get shadowsocks image and run it
  hosts: "{{instance}}"
  gather_facts: true
  become: yes
  # connection: local
  user: "{{user}}"
  pre_tasks:
  # - name: check if docker is installed
  #   shell: dpkg -l | grep docker
  #   register: docker_check
  #   failed_when: "docker_check.rc == 2 or docker_check.rc == 3"
  #   when: ansible_os_family == 'Debian'
  # - name: check if docker is installed
  #   shell: rpm -qa | grep docker
  #   register: docker_check
  #   failed_when: "docker_check.rc == 2 or docker_check.rc == 3"
  #   when: ansible_os_family == 'RedHat'
  - name: debug
    # debug: "{{hostvars[groups[instance][0]]}}"
    # shell: echo "{{hostvars[groups[instance][0]]['dev_node_key_name']}}"
    shell: echo "{{inventory_hostname}}"